### ISSUE TITLE
How to set up the environment variables on macOS?

### ISSUE THREAD

**Issue by bnejy** [poohcom1/tank-turn-tactics#3]
I tried the method you mentioned in the Setup, but as on macOS you cannot start a file with a full stop. How should I set up the environment variables?

**Comment by poohcom1** [comment]
I'm not familiar with macOS at all, but I think you can create the .env by using the terminal. Trying rename the sample.env or create a file from within vs code

**Comment by bnejy** [comment]
Thanks, I'll try that.

**Comment by bnejy** [comment]
Using the mv command worked.
